name: node
on:
   push:
     branches: [main]
   workflow_dispatch:
jobs:
  npm-install:
    runs-on: [ubuntu-latest]
    steps:

    - name: setup node
      uses:  actions/setup-node@v3
      with:
        node-version: 18

    - name: verify node
      run: |
        node --version
        npm --version
        npm cache clean --force
        npm cache verify
        echo "install octokit"
        npm install @octokit/auth-app
        npm install @octokit/request
        echo "git setup"        
        pwd
        git init
        # git config --global --add safe.directory /__w/node-code/node-code
        git config --global user.name "hiren"
        git config --global url.https://${{ secrets.git_pat }}@github.com/
        git config --global user.email "hirenparghi90@gmail.com"
        git remote add origin https://github.com/hirenrparghi/node-code
        # git remote add origin https://hirenrparghi:Profit@221176@github.com/hirenrparghi/node.git
        git add .
        git commit -m "publish node modules"
        git config --global http.sslverify false
        git checkout -b main
        git push origin main --force
      
        
        
    
  
     
